### ISSUE TITLE
Create table component

### ISSUE THREAD

**Issue by laurensgroeneveld** [bcc-code/bcc-design-library#152]
<img width="643" alt="image" src="https://github.com/bcc-code/bcc-design-library/assets/39056299/7381d5de-09ae-48d9-a10b-77a148000597">

## Acceptance Criteria:

- Create a Table component, with any needed generic subcomponents (disregard A-team-specific components for now)

**Comment by u12206050** [comment]
@laurensgroeneveld Here is a table component I created that is quite optimised to handle a ton of rows.
It supports adding additional append slots for actions, as well as custom components.
https://github.com/bcc-code/bcc-events-cms/blob/master/packages/modules/activities/src/shared/FastTable.vue

**Comment by laurensgroeneveld** [comment]
> @laurensgroeneveld Here is a table component I created that is quite optimised to handle a ton of rows. It supports adding additional append slots for actions, as well as custom components. https://github.com/bcc-code/bcc-events-cms/blob/master/packages/modules/activities/src/shared/FastTable.vue

Thanks, this has a lot of useful stuff 👍 I'll probably go a bit more of the HeadlessUI approach with some subcomponents like `TableHeading` or `TableCell` just to make it easier to use markup with custom components.
